export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  mode: 'dark' | 'light';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  fontFamily: string;
  previewColors: string[];
}

export const THEME_PRESETS: ThemePreset[] = [
  // --- DARK THEMES ---
  {
    id: 'amber-nocturne',
    name: '01. Lumina Amber Nocturne',
    description: 'Cinematic deep obsidian black with warm golden amber highlights and slate accents.',
    mode: 'dark',
    primaryColor: '#f59e0b',
    secondaryColor: '#0f172a',
    accentColor: '#fbbf24',
    fontFamily: 'Playfair Display, serif',
    previewColors: ['#0f172a', '#f59e0b', '#fbbf24'],
  },
  {
    id: 'vogue-noir',
    name: '02. Vogue Noir & Monochrome',
    description: 'High-fashion editorial monochrome with pure ivory typography and obsidian contrast.',
    mode: 'dark',
    primaryColor: '#ffffff',
    secondaryColor: '#09090b',
    accentColor: '#e4e4e7',
    fontFamily: 'Cinzel, serif',
    previewColors: ['#09090b', '#ffffff', '#e4e4e7'],
  },
  {
    id: 'emerald-royale',
    name: '03. Emerald Royale & Velvet',
    description: 'Botanical luxury with deep forest green tones, mint luminescence, and gold details.',
    mode: 'dark',
    primaryColor: '#10b981',
    secondaryColor: '#022c22',
    accentColor: '#34d399',
    fontFamily: 'Cormorant Garamond, serif',
    previewColors: ['#022c22', '#10b981', '#34d399'],
  },
  {
    id: 'champagne-rose',
    name: '04. Champagne & Rose Gold',
    description: 'Romantic fine-art wedding aesthetic with warm rose gold, blush tones, and dark velvet.',
    mode: 'dark',
    primaryColor: '#fb7185',
    secondaryColor: '#1f1924',
    accentColor: '#f43f5e',
    fontFamily: 'Bodoni Moda, serif',
    previewColors: ['#1f1924', '#fb7185', '#f43f5e'],
  },
  {
    id: 'sapphire-obsidian',
    name: '05. Sapphire Obsidian',
    description: 'Corporate summit & high-tech luxury with deep ocean obsidian and electric cyan.',
    mode: 'dark',
    primaryColor: '#38bdf8',
    secondaryColor: '#0c4a6e',
    accentColor: '#0ea5e9',
    fontFamily: 'Space Grotesk, sans-serif',
    previewColors: ['#0c4a6e', '#38bdf8', '#0ea5e9'],
  },
  {
    id: 'amethyst-twilight',
    name: '06. Amethyst Twilight',
    description: 'Avant-garde fashion and editorial mystery featuring deep violet and amethyst glow.',
    mode: 'dark',
    primaryColor: '#c084fc',
    secondaryColor: '#1e1b4b',
    accentColor: '#a855f7',
    fontFamily: 'Syne, sans-serif',
    previewColors: ['#1e1b4b', '#c084fc', '#a855f7'],
  },
  {
    id: 'bronze-heritage',
    name: '07. Bronze Heritage & Terracotta',
    description: 'Artisan architectural aesthetic with burnt terracotta, warm copper, and dark stone.',
    mode: 'dark',
    primaryColor: '#ea580c',
    secondaryColor: '#1c1917',
    accentColor: '#f97316',
    fontFamily: 'Cinzel Decorative, serif',
    previewColors: ['#1c1917', '#ea580c', '#f97316'],
  },
  {
    id: 'minimalist-sand',
    name: '08. Minimalist Sand & Quartz',
    description: 'Nordic architectural warm minimalism with golden sand and charcoal quartz balance.',
    mode: 'dark',
    primaryColor: '#d97706',
    secondaryColor: '#18181b',
    accentColor: '#f59e0b',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    previewColors: ['#18181b', '#d97706', '#f59e0b'],
  },
  {
    id: 'cyberpunk-neon',
    name: '09. Cyberpunk Neon Studio',
    description: 'Futuristic commercial photography with neon crimson, cyber teal, and dark grid background.',
    mode: 'dark',
    primaryColor: '#f43f5e',
    secondaryColor: '#0f172a',
    accentColor: '#06b6d4',
    fontFamily: 'Syncopate, sans-serif',
    previewColors: ['#0f172a', '#f43f5e', '#06b6d4'],
  },
  {
    id: 'solaris-golden-hour',
    name: '10. Solaris Golden Hour',
    description: 'Sunset warmth fine art studio with golden sun radiance and dark violet dusk.',
    mode: 'dark',
    primaryColor: '#eab308',
    secondaryColor: '#1a1625',
    accentColor: '#facc15',
    fontFamily: 'Italiana, serif',
    previewColors: ['#1a1625', '#eab308', '#facc15'],
  },

  // --- LIGHT THEMES ---
  {
    id: 'ivory-gold-light',
    name: '11. Parisian Ivory & Fine Gold (Light)',
    description: 'Ultra-luxurious light theme with warm cream ivory canvas, charcoal serif typography, and brushed gold accents.',
    mode: 'light',
    primaryColor: '#b45309',
    secondaryColor: '#fafaf9',
    accentColor: '#d97706',
    fontFamily: 'Playfair Display, serif',
    previewColors: ['#fafaf9', '#b45309', '#d97706'],
  },
  {
    id: 'porcelain-charcoal-light',
    name: '12. Nordic Porcelain & Slate (Light)',
    description: 'Clean architectural minimalism with crisp porcelain white background, slate typography, and sky blue accents.',
    mode: 'light',
    primaryColor: '#0284c7',
    secondaryColor: '#f8fafc',
    accentColor: '#0369a1',
    fontFamily: 'Inter, sans-serif',
    previewColors: ['#f8fafc', '#0284c7', '#0369a1'],
  },
  {
    id: 'blush-pearl-light',
    name: '13. Atelier Blush Pearl & Quartz (Light)',
    description: 'Soft romantic wedding light palette featuring subtle pearl pink canvas, warm rose gold, and soft espresso text.',
    mode: 'light',
    primaryColor: '#e11d48',
    secondaryColor: '#fff1f2',
    accentColor: '#f43f5e',
    fontFamily: 'Cormorant Garamond, serif',
    previewColors: ['#fff1f2', '#e11d48', '#f43f5e'],
  },
  {
    id: 'sage-linen-light',
    name: '14. Botanical Sage & Natural Linen (Light)',
    description: 'Organic editorial warmth with pale sage linen canvas, deep forest green accents, and spring leaf details.',
    mode: 'light',
    primaryColor: '#059669',
    secondaryColor: '#f0fdf4',
    accentColor: '#10b981',
    fontFamily: 'Bodoni Moda, serif',
    previewColors: ['#f0fdf4', '#059669', '#10b981'],
  },
  {
    id: 'carrara-sun-light',
    name: '15. Carrara Marble & Terracotta (Light)',
    description: 'Mediterranean sunlit gallery featuring cool white marble canvas, rich terracotta highlights, and bronze contrast.',
    mode: 'light',
    primaryColor: '#c2410c',
    secondaryColor: '#fdfbf7',
    accentColor: '#ea580c',
    fontFamily: 'Cinzel, serif',
    previewColors: ['#fdfbf7', '#c2410c', '#ea580c'],
  },
];
